utils/clone: add --ignore-whitespace to gsutil.patch apply
fixes applying this patch on windows, otherwise it fails with:

    INFO: Updating gsutil submodules
    error: patch failed: gslib/commands/cp.py:1043
    error: gslib/commands/cp.py: patch does not apply
    error: patch failed: gsutil.py:27
    error: gsutil.py: patch does not apply

I assume it breaks due to some LF/CRLF conflict, which is why this flag
is already used for the gclient patch above.