CI: fix version check workflow by url encoding filter in url
This workflow stated consistently failing roughly one week ago.
Unfortunately the Workflow on GitHub has no error logs besides

~~~
Error: Process completed with exit code 92.
~~~

which isn't particularly helpful.

The issue can, however, be reproduced by simply copying parts of the
workflow into a local bash script and executing that.

As it turns out, the issue lays in `?filter=fraction>=0.5` when using
`curl` due to missing url encoding.

~~~
# curl 'https://versionhistory.googleapis.com/v1/chrome/platforms/linux/channels/stable/versions/all/releases?filter=fraction>=0.5'
curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
~~~

vs

~~~
# curl -s 'https://versionhistory.googleapis.com/v1/chrome/platforms/linux/channels/stable/versions/all/releases?filter=fraction%3E=0.5' | wc -l
3128
~~~